name: Deploy

on:
  workflow_dispatch:

jobs:
  run-tests:
    uses: ./.github/workflows/tests.yml

  deploy:
    needs: run-tests
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Display Deployment Message
        run: echo "Deployed"
