name: Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - 'backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - 'backend/**'

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/
    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Run Jest tests
      run: npm test
      env:
        CI: true
      continue-on-error: true
    - name: Publish Test Summary Results
      if: always()
      run: npx github-actions-ctrf ctrf/ctrf-report.json 
    - name: Check test results
      if: always()
      run: |
        if grep -q '"failed": 0,' ctrf/ctrf-report.json; then
          echo "All tests passed."
        else
          echo "Some tests failed."
          exit 1
        fi

  frontend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/
    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Run Jest tests
      run: npm test
      env:
        CI: true
      continue-on-error: true
    - name: Publish Test Summary Results
      if: always()
      run: npx github-actions-ctrf ctrf/ctrf-report.json 
    - name: Check test results
      if: always()
      run: |
        if grep -q '"failed": 0,' ctrf/ctrf-report.json; then
          echo "All tests passed."
        else
          echo "Some tests failed."
          exit 1
        fi